/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab2;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class InterfazCal extends javax.swing.JFrame {
DefaultTableModel modelo1 = new DefaultTableModel();
DefaultTableModel modelo2 = new DefaultTableModel();
DefaultTableModel modelo3 = new DefaultTableModel();
Calculadora teclado = new Calculadora();
    /**
     * Creates new form InterfazCal
     */
    public InterfazCal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Calculadora De Matrices");

        jLabel2.setText("?x?");

        jTable1.setModel(modelo2);
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(modelo1);
        jScrollPane2.setViewportView(jTable2);

        jButton2.setText("Suma");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable3.setModel(modelo3);
        jScrollPane3.setViewportView(jTable3);

        jButton1.setText("=");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Resta");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Multiplicacion");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("A*b^1");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jButton3)
                        .addGap(66, 66, 66)
                        .addComponent(jButton4)
                        .addGap(29, 29, 29)
                        .addComponent(jButton5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        String tabla = jTextField1.getText();
        String[] ficol;
        ficol = tabla.split("x");
  
        modelo1.setColumnCount(Integer.parseInt(ficol[1]));
        modelo1.setRowCount(Integer.parseInt(ficol[0]));
        modelo2.setColumnCount(Integer.parseInt(ficol[1]));
        modelo2.setRowCount(Integer.parseInt(ficol[0]));
        modelo3.setColumnCount(Integer.parseInt(ficol[1]));
        modelo3.setRowCount(Integer.parseInt(ficol[0]));
        
        teclado.setfilas(Integer.parseInt(ficol[0]));
        teclado.setcolumnas(Integer.parseInt(ficol[1]));
        teclado.setopcion(1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:
    switch (teclado.getopcion()) {
        case 1:
            {
                int c;
                for(int i=0;i<teclado.getfilas();i++){
                    for(int j=0;j<teclado.getcolumnas();j++){
                        c = Integer.parseInt(modelo1.getValueAt(i, j).toString()) + Integer.parseInt(modelo2.getValueAt(i, j).toString());
                        modelo3.setValueAt(c, i, j);
                    }
                }         break;
            }
        case 2:
            {
                int c;
                for(int i=0;i<teclado.getfilas();i++){
                    for(int j=0;j<teclado.getcolumnas();j++){
                        c = Integer.parseInt(modelo1.getValueAt(i, j).toString()) - Integer.parseInt(modelo2.getValueAt(i, j).toString());
                        modelo3.setValueAt(c, i, j);
                    }
                }         break;
            }
        case 3:
            {
                int c;
                for(int i=0;i<teclado.getfilas();i++){
                    for(int j=0;j<teclado.getcolumnas();j++){
                        c = Integer.parseInt(modelo1.getValueAt(i, j).toString()) * Integer.parseInt(modelo2.getValueAt(i, j).toString());
                        modelo3.setValueAt(c, i, j);
                    }
                }         break;
            }
        case 4:
        {
            if(teclado.getfilas()==3 && teclado.getcolumnas()==3){
         int a,b,c,d,e;
         
         a = (Integer.parseInt(modelo1.getValueAt(1,1).toString())*Integer.parseInt(modelo1.getValueAt(2,2).toString()))-(Integer.parseInt(modelo1.getValueAt(1,2).toString())*Integer.parseInt(modelo1.getValueAt(2,1).toString()));
         b = (Integer.parseInt(modelo1.getValueAt(1,0).toString())*Integer.parseInt(modelo1.getValueAt(2,2).toString()))-(Integer.parseInt(modelo1.getValueAt(1,2).toString())*Integer.parseInt(modelo1.getValueAt(2,0).toString()));
         c = (Integer.parseInt(modelo1.getValueAt(1,0).toString())*Integer.parseInt(modelo1.getValueAt(2,1).toString()))-(Integer.parseInt(modelo1.getValueAt(1,1).toString())*Integer.parseInt(modelo1.getValueAt(2,0).toString()));
         d = (Integer.parseInt(modelo1.getValueAt(0,0).toString())*a)-(Integer.parseInt(modelo1.getValueAt(0,1).toString())*b)+(Integer.parseInt(modelo1.getValueAt(0,2).toString())*c);
                for(int i=0;i<teclado.getfilas();i++){
                    for(int j=0;j<teclado.getcolumnas();j++){
                        e= Integer.parseInt(modelo1.getValueAt(i,j).toString());
                       modelo3.setValueAt(e+"/"+d, i, j);
                    }
                }   
        }else
                if(teclado.getfilas()==2 && teclado.getcolumnas()==2){
                    int a,b;
                 a = (Integer.parseInt(modelo1.getValueAt(0,0).toString())*Integer.parseInt(modelo1.getValueAt(1,1).toString()))-(Integer.parseInt(modelo1.getValueAt(0,1).toString())*Integer.parseInt(modelo1.getValueAt(1,0).toString()));
                 for(int i=0;i<teclado.getfilas();i++){
                    for(int j=0;j<teclado.getcolumnas();j++){
                        b = Integer.parseInt(modelo1.getValueAt(i,j).toString());
                       modelo3.setValueAt((b+"/"+a), i, j);
                    }
                }   
                }
                else 
                     modelo3.setValueAt("error", 0, 0);
        
        }
        
            break;
        default:
            break;
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         String tabla = jTextField1.getText();
        String[] ficol;
        ficol = tabla.split("x");
  
        modelo1.setColumnCount(Integer.parseInt(ficol[1]));
        modelo1.setRowCount(Integer.parseInt(ficol[0]));
        modelo2.setColumnCount(Integer.parseInt(ficol[1]));
        modelo2.setRowCount(Integer.parseInt(ficol[0]));
        modelo3.setColumnCount(Integer.parseInt(ficol[1]));
        modelo3.setRowCount(Integer.parseInt(ficol[0]));
        
        teclado.setfilas(Integer.parseInt(ficol[0]));
        teclado.setcolumnas(Integer.parseInt(ficol[1]));
        teclado.setopcion(2);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         String tabla = jTextField1.getText();
        String[] ficol;
        ficol = tabla.split("x");
  
        modelo1.setColumnCount(Integer.parseInt(ficol[1]));
        modelo1.setRowCount(Integer.parseInt(ficol[0]));
        modelo2.setColumnCount(Integer.parseInt(ficol[1]));
        modelo2.setRowCount(Integer.parseInt(ficol[0]));
        modelo3.setColumnCount(Integer.parseInt(ficol[1]));
        modelo3.setRowCount(Integer.parseInt(ficol[0]));
        
        teclado.setfilas(Integer.parseInt(ficol[0]));
        teclado.setcolumnas(Integer.parseInt(ficol[1]));
        teclado.setopcion(3);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         String tabla = jTextField1.getText();
        String[] ficol;
        ficol = tabla.split("x");
  
        modelo1.setColumnCount(Integer.parseInt(ficol[1]));
        modelo1.setRowCount(Integer.parseInt(ficol[0]));
        modelo2.setColumnCount(Integer.parseInt(ficol[1]));
        modelo2.setRowCount(Integer.parseInt(ficol[0]));
        modelo3.setColumnCount(Integer.parseInt(ficol[1]));
        modelo3.setRowCount(Integer.parseInt(ficol[0]));
        
        teclado.setfilas(Integer.parseInt(ficol[0]));
        teclado.setcolumnas(Integer.parseInt(ficol[1]));
        teclado.setopcion(4);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazCal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazCal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazCal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazCal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazCal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
